import ProjectDescription

let workspace = Workspace(
  name: "SwiftMusicTheory",
  projects: ["."],
  generationOptions: .options(enableAutomaticXcodeSchemes: false, autogeneratedWorkspaceSchemes: .disabled)
)
